Add CVE-2021-3564
evdenis/cvehound pull request #19
Opened 2021-06-28 19:56 UTC by MenV1S

Попробовал добавить свой детект для уязвимости. Протестировал на версиях 3.12.9 (еще не появилась), 3.13 (уязвима), 4.14.194(уязвима), 4.14.236 (исправлена)

2021-06-29 06:51 UTC, evdenis commented
Commit message says that this is CVE-2017-3564, but the filename describes it as CVE-2021-3564.

2021-06-29 08:55 UTC, evdenis requested changes
In the the rule should like these:
```
/// Files: net/bluetooth/hci_core.c
/// Fix: 6a137caec23aeb9e036cdfd8a46dd8a366460e5d
/// Detect-To: b78752cc71d86998d3b77d873c61d6ffdb7a2142

virtual detect

@err exists@
identifier hdev;
position p;
@@

\(hci_dev_open\|hci_dev_do_open\)(...)
{
        ...
*       \(flush_work@p\|tasklet_kill@p\)(&hdev->\(cmd_work\|cmd_task\));
        \(flush_work\|tasklet_kill\)(&hdev->\(rx_work\|rx_task\));
        ...
}


@script:python depends on detect@
p << err.p;
@@

coccilib.report.print_report(p[0], 'ERROR: CVE-2021-3564')
```

And pass the tests with:
```
$ pytest --cve CVE-2021-3564
$ pytest --cve CVE-2021-3564 --runslow
```

2021-06-29 08:55 UTC, evdenis commented on cvehound/cve/CVE-2021-3564.cocci
> +/// Fixes: 6a137caec23aeb9e036cdfd8a46dd8a366460e5d
```
/// Fix: 6a137caec23aeb9e036cdfd8a46dd8a366460e5d
/// Detect-To: b78752cc71d86998d3b77d873c61d6ffdb7a2142
```

2021-06-29 08:55 UTC, evdenis commented on cvehound/cve/CVE-2021-3564.cocci
> +/// Fixes: 6a137caec23aeb9e036cdfd8a46dd8a366460e5d
b78752cc71d86998d3b77d873c61d6ffdb7a2142 seems like the commit where the bug appeared the first time

2021-06-29 08:55 UTC, evdenis commented on cvehound/cve/CVE-2021-3564.cocci
> +}
I would write it like this
```
@err exists@
identifier hdev;
position p;
@@

\(hci_dev_open\|hci_dev_do_open\)(...)
{
        ...
*       \(flush_work@p\|tasklet_kill@p\)(&hdev->\(cmd_work\|cmd_task\));
        \(flush_work\|tasklet_kill\)(&hdev->\(rx_work\|rx_task\));
        ...
}
```

2021-06-29 08:55 UTC, evdenis commented on cvehound/cve/CVE-2021-3564.cocci
> +p << err.p_cmd_flush;
p << err.p;

2021-06-29 08:55 UTC, evdenis commented on cvehound/cve/CVE-2021-3564.cocci
> +coccilib.report.print_report(p[0], 'ERROR: CVE-2021-3564')
because there is already p[0] here

2021-06-29 18:30 UTC, MenV1S commented on cvehound/cve/CVE-2021-3564.cocci
> +/// Fixes: 6a137caec23aeb9e036cdfd8a46dd8a366460e5d
If we added tasklet_call function into the rule shouldn't we change 'Detect-To' field?

2021-06-29 19:34 UTC, evdenis commented on cvehound/cve/CVE-2021-3564.cocci
> +/// Fixes: 6a137caec23aeb9e036cdfd8a46dd8a366460e5d
Commit b78752cc71d86998d3b77d873c61d6ffdb7a2142 contains tasklet_kill() function call.

2021-06-29 19:36 UTC, evdenis commented
Please, push the changes and I'll merge the rule.

2021-06-30 21:46 UTC, evdenis commented
Merged, thanks! https://github.com/evdenis/cvehound/commit/68822be41e7984e9212a890242d353edcdc769e5

2021-06-30 21:46 UTC, closed without merging